pipeline {
    agent any
    tools { maven 'Maven3' }

    stages {
        stage('Build & Tests') {
            steps {
                echo 'Compilation et tests unitaires...'
                sh 'mvn -B clean verify'
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube-pfa') {
                    sh '''mvn -B sonar:sonar \
                      -Dsonar.projectKey=pfa-backend \
                      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml'''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build JAR') {
            steps {
                sh 'mvn -B package -DskipTests'
            }
        }
    }

    post {
        success { echo 'Pipeline SUCCESS' }
        failure { echo 'Pipeline FAILED, consulte la Console Output' }
    }
}