--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._user (
    account_locked boolean NOT NULL,
    enabled boolean NOT NULL,
    failed_attempts integer NOT NULL,
    lock_level integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) without time zone,
    locked_until timestamp(6) without time zone,
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255),
    provider character varying(255),
    CONSTRAINT _user_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[])))
);


--
-- Name: _user_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._user_tokens (
    tokens_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    id bigint NOT NULL
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client (
    notifications_enabled boolean NOT NULL,
    onboarding_completed boolean NOT NULL,
    id bigint NOT NULL,
    last_active_at timestamp(6) without time zone,
    company character varying(255),
    job_title character varying(255),
    notification_frequency character varying(255),
    profile_picture character varying(255),
    CONSTRAINT client_notification_frequency_check CHECK (((notification_frequency)::text = ANY ((ARRAY['REALTIME'::character varying, 'DAILY_SUMMARY'::character varying, 'WEEKLY_SUMMARY'::character varying])::text[])))
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    profile_picture character varying(500)
);


--
-- Name: external_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.external_connection (
    client_id bigint NOT NULL,
    connected_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_sync_at timestamp(6) without time zone,
    access_token character varying(2048),
    refresh_token character varying(2048),
    external_url character varying(255),
    external_username character varying(255),
    provider character varying(255),
    CONSTRAINT external_connection_provider_check CHECK (((provider)::text = ANY ((ARRAY['GITHUB'::character varying, 'SONARQUBE'::character varying, 'JENKINS'::character varying])::text[])))
);


--
-- Name: external_connection_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.external_connection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.external_connection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    read boolean NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    tracked_repo_id bigint NOT NULL,
    commitsha character varying(255),
    message character varying(255),
    type character varying(255),
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['COMMIT'::character varying, 'BUILD'::character varying, 'SONARQUBE'::character varying])::text[])))
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_push_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_push_token (
    client_id bigint NOT NULL,
    id bigint NOT NULL,
    registered_at timestamp(6) without time zone,
    expo_push_token character varying(255) NOT NULL
);


--
-- Name: notification_push_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_push_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_push_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: push_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.push_tokens (
    id bigint NOT NULL,
    expo_push_token character varying(255) NOT NULL,
    registered_at timestamp(6) without time zone,
    client_id bigint NOT NULL
);


--
-- Name: push_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.push_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.push_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    revoked boolean NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(512) NOT NULL
);


--
-- Name: refresh_token_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.refresh_token_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_modified_at timestamp(6) without time zone,
    name character varying(255)
);


--
-- Name: role_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.role_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token (
    expired boolean NOT NULL,
    revoked boolean NOT NULL,
    create_at timestamp(6) without time zone,
    expired_at timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    validate_at timestamp(6) without time zone,
    token character varying(2048)
);


--
-- Name: token_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.token_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tracked_repository; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tracked_repository (
    client_id bigint NOT NULL,
    external_repo_id bigint,
    id bigint NOT NULL,
    tracked_at timestamp(6) without time zone,
    full_name character varying(255),
    jenkins_job_name character varying(255),
    name character varying(255),
    provider character varying(255),
    sonar_project_key character varying(255),
    url character varying(255),
    CONSTRAINT tracked_repository_provider_check CHECK (((provider)::text = ANY ((ARRAY['GITHUB'::character varying, 'SONARQUBE'::character varying, 'JENKINS'::character varying])::text[])))
);


--
-- Name: tracked_repository_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tracked_repository ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracked_repository_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_roles (
    _user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: _user _user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._user
    ADD CONSTRAINT _user_email_key UNIQUE (email);


--
-- Name: _user _user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._user
    ADD CONSTRAINT _user_pkey PRIMARY KEY (id);


--
-- Name: _user_tokens _user_tokens_tokens_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._user_tokens
    ADD CONSTRAINT _user_tokens_tokens_id_key UNIQUE (tokens_id);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: external_connection external_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_connection
    ADD CONSTRAINT external_connection_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: notification_push_token notification_push_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_push_token
    ADD CONSTRAINT notification_push_token_pkey PRIMARY KEY (id);


--
-- Name: push_tokens push_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.push_tokens
    ADD CONSTRAINT push_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_token_hash_key UNIQUE (token_hash);


--
-- Name: role role_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_name_key UNIQUE (name);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- Name: tracked_repository tracked_repository_client_id_external_repo_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracked_repository
    ADD CONSTRAINT tracked_repository_client_id_external_repo_id_key UNIQUE (client_id, external_repo_id);


--
-- Name: tracked_repository tracked_repository_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracked_repository
    ADD CONSTRAINT tracked_repository_pkey PRIMARY KEY (id);


--
-- Name: tracked_repository uk92s92yr6qlabeg81r1n2u1qv2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracked_repository
    ADD CONSTRAINT uk92s92yr6qlabeg81r1n2u1qv2 UNIQUE (client_id, external_repo_id);


--
-- Name: external_connection fk48e8ai61g2dyr0oa8gkl5r9bq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_connection
    ADD CONSTRAINT fk48e8ai61g2dyr0oa8gkl5r9bq FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: admins fk4wo25pbi2oxpt57tc96r7892c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT fk4wo25pbi2oxpt57tc96r7892c FOREIGN KEY (id) REFERENCES public._user(id);


--
-- Name: notification_push_token fk5w5pl8e1xfv367li7myuql6lv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_push_token
    ADD CONSTRAINT fk5w5pl8e1xfv367li7myuql6lv FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: _user_tokens fk7vomh1dju9u2humjhhl253888; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._user_tokens
    ADD CONSTRAINT fk7vomh1dju9u2humjhhl253888 FOREIGN KEY (user_id) REFERENCES public._user(id);


--
-- Name: notification fk9dtvajp4yqax0tjgvggnpb98o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk9dtvajp4yqax0tjgvggnpb98o FOREIGN KEY (tracked_repo_id) REFERENCES public.tracked_repository(id);


--
-- Name: tracked_repository fka7u47eks4ty5x70n1p7a3sa3t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracked_repository
    ADD CONSTRAINT fka7u47eks4ty5x70n1p7a3sa3t FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: refresh_token fkbws85up72jgwebb6ttkjiytg3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkbws85up72jgwebb6ttkjiytg3 FOREIGN KEY (user_id) REFERENCES public._user(id);


--
-- Name: _user_tokens fkd3ir35qlkkwv0t44hexphxj4d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._user_tokens
    ADD CONSTRAINT fkd3ir35qlkkwv0t44hexphxj4d FOREIGN KEY (tokens_id) REFERENCES public.token(id);


--
-- Name: notification fki632mmj44t1ofv24dgvqbth1r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fki632mmj44t1ofv24dgvqbth1r FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: token fkiblu4cjwvyntq3ugo31klp1c6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fkiblu4cjwvyntq3ugo31klp1c6 FOREIGN KEY (user_id) REFERENCES public._user(id);


--
-- Name: users_roles fkimxexaklygampb37o1mpjigtk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkimxexaklygampb37o1mpjigtk FOREIGN KEY (_user_id) REFERENCES public._user(id);


--
-- Name: client fkksnnly16o8nnnic4m2mfa1rl7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkksnnly16o8nnnic4m2mfa1rl7 FOREIGN KEY (id) REFERENCES public._user(id);


--
-- Name: users_roles fkt4v0rrweyk393bdgt107vdx0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkt4v0rrweyk393bdgt107vdx0x FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--


