version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
