spring.application.name=Spring App

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-db:5432/demo_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Configuration JWT de sécurité
application.security.secret-key=${JWT_SECRET_KEY}
application.security.access-expiration=${JWT_ACCESS_EXPIRATION:300000}
application.security.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Mail Config
spring.mail.host=${MAIL_HOST:mailhog}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# URLs Frontend
application.mailing.frontend.activation-url=${FRONTEND_ACTIVATION_URL:http://localhost:4200/activate-account}
application.mailing.frontend.reset-password-url=${FRONTEND_RESET_PASSWORD_URL:http://localhost:4200/reset-password-url}

# Google OAuth
google.client.id=${GOOGLE_CLIENT_ID}

# GitHub OAuth
github.oauth.client-id=${GITHUB_CLIENT_ID}
github.oauth.client-secret=${GITHUB_CLIENT_SECRET}
github.oauth.redirect-uri=${GITHUB_REDIRECT_URI}
github.oauth.authorize-url=https://github.com/login/oauth/authorize
github.oauth.token-url=https://github.com/login/oauth/access_token
github.oauth.user-api-url=https://api.github.com/user

# GitHub Webhooks & Encryption
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}
app.webhook.github-url=${APP_GITHUB_WEBHOOK_URL}
app.encryption.secret-key=${APP_ENCRYPTION_SECRET_KEY}